RANDOM = [
    "https://www.youtube.com/watch?v=M7X6oYg6iro", # Indochine - L'aventurier
    "https://www.youtube.com/watch?v=IkU158B5VzQ", # Celine Dion & Garou - Sous Le Vent
    "https://www.youtube.com/watch?v=Y9GCM9DZUJo", # Claudio Capéo - Un homme debout
    "https://www.youtube.com/watch?v=E7bgWEAMdwo", # Daniel Balavoine - Vivre ou survivre
    "https://www.youtube.com/watch?v=yqzMim3Sn3s", # Alain Souchon - Foule Sentimentale
    "https://www.youtube.com/watch?v=jmvt4B8rK2U", # Téléphone - Cendrillon
    "https://www.youtube.com/watch?v=80hMEKlLVgQ", # Manau - La tribu de Dana
    "https://www.youtube.com/watch?v=VQd1IOyhKS4", # Hugues aufray - Santiano
    "https://www.youtube.com/watch?v=ZyhrYis509A", # Aqua - Barbie Girl
    "https://www.youtube.com/watch?v=jofNR_WkoCE", # Ylvis - The Fox
    "https://www.youtube.com/watch?v=U0fk5L1ifbo", # Eiffel 65 - Blue
    "https://www.youtube.com/watch?v=y6120QOlsfU", # Darude - Sandstorm
    "https://www.youtube.com/watch?v=CwdrtwZiQ9E", # Black Eyes Peas - I Gotta Feeling
    "https://www.youtube.com/watch?v=HqK4-dIiKY8", # Lady Gaga - Poker Face
    "https://www.youtube.com/watch?v=tscL_I2v7pU", # Spice Girls - Wannabe
    "https://www.youtube.com/watch?v=tVdr_JWmnsA", # Britney Spears - Toxic
    "https://www.youtube.com/watch?v=fWNaR-rxAic", # Carly Rae Jepsen - Call Me Maybe
    "https://www.youtube.com/watch?v=kVpv8-5XWOI", # Train - Hey, Soul Sister
    "https://www.youtube.com/watch?v=hT_nvWreIhg", # OneRepublic - Counting Stars
    "https://www.youtube.com/watch?v=_ovdm2yX4MA", # Avicii - Levels
    "https://www.youtube.com/watch?v=pVHKp6ffURY", # Scatman - Scatman
    "https://www.youtube.com/watch?v=f7P5Q2IIT4U", # O-Zone - Dragostea din tei
    "https://www.youtube.com/watch?v=AMT698ArSfQ", # Las Ketchup - The Ketchup Song
    "https://www.youtube.com/watch?v=eTq88V1xJ-E", # Vengaboys - Boom, Boom, Boom, Boom!!
    "https://www.youtube.com/watch?v=XispGbJqwjQ", # Haddaway - What Is Love
    "https://www.youtube.com/watch?v=iQEpTa3VqLU", # Boney M - Daddy Cool
    "https://www.youtube.com/watch?v=RN8Li7kYNnw", # Village People - YMCA
    "https://www.youtube.com/watch?v=MIgK3zOk0zg", # a-ha - Take on me
    "https://www.youtube.com/watch?v=NNiTxUEnmKI", # Europe - The Final Countdown
    "https://www.youtube.com/watch?v=Ea5rb6__yms", # Nirvana - Smells Like Teen Spirit
    "https://www.youtube.com/watch?v=SYnVYJDxu2Q", # Boney M. - Rasputin
    "https://www.youtube.com/watch?v=I_izvAbhExY", # Bee Gees - Stayin' Alive
    "https://www.youtube.com/watch?v=qeMFqkcPYcg", # Eurythmics - Sweet Dreams
    "https://www.youtube.com/watch?v=5NV6Rdv1a3I", # Daft Punk - Get Lucky
    "https://www.youtube.com/watch?v=tCnBrrnOefs", # Justice - D.A.N.C.E
    "https://www.youtube.com/watch?v=SPlQpGeTbIE", # Junior Senior - Move Your Feet
    "https://www.youtube.com/watch?v=tolm-07if3c", # The Ting Tings - Shut Up and Let Me Go
    "https://www.youtube.com/watch?v=8mCLc332sTM", # SAULE - Dusty Men
    "https://www.youtube.com/watch?v=3X-KbPmOx8s", # Bénabar - Le diner
    "https://www.youtube.com/watch?v=aoiuUJ6JqWQ", # Gold - Capitaine abandonné
    "https://www.youtube.com/watch?v=NvS351QKFV4", # Dschinghis Khan - Moskau
    "https://www.youtube.com/watch?v=EK_LN3XEcnw", # Lou Bega - Mambo No. 5
    "https://www.youtube.com/watch?v=p_ZxDNZjzVk", # Images - Les Démons de Minuit
    "https://www.youtube.com/watch?v=mOYZaiDZ7BM", # Rednex - Cotton Eye Joe
    "https://www.youtube.com/watch?v=AS4GlgkW5Fc", # Fatal Bazooka - Ce matin va être une pure soirée
    "https://www.youtube.com/watch?v=TYgOlqinH7A", # Witch Doctor - Ooh Eeh Ooh Ah Aah Ting Tang Walla Walla Bing
    "https://www.youtube.com/watch?v=GafCMV4pOaY", # Bronzé - Y'a du Soleil et des Nanas
    "https://www.youtube.com/watch?v=j-48Xg2cKyg", # La Compagnie Créole - Le Bal Masqué
    "https://www.youtube.com/watch?v=GEnNpqYdgTk", # Patrick Sébastien - Les Sardines
    "https://www.youtube.com/watch?v=qY_3i59b8g4", # Partenaire Particulier
    "https://www.youtube.com/watch?v=9J9haehfQeg", # Ghostbusters
    "https://www.youtube.com/watch?v=JhulBGMA7G4", # Daft Punk - Harder, Better, Faster, Stronger
    "https://www.youtube.com/watch?v=PdaAHMztNVE", # Stupeflip - Stupeflip Vite
    "https://www.youtube.com/watch?v=1b0Eh4iELqQ", # Casseurs Flowters - A l'heure ou je me couche
    "https://www.youtube.com/watch?v=JSG2qHBm7WM", # MC Solaar - Nouveau Western
    "https://www.youtube.com/watch?v=znSs7uEXCeo", # Tryo — Désolé pour hier soir
    "https://www.youtube.com/watch?v=LZPT5_k5Al4", # Les Fatals Picards - La Sécurité de l'Emploi
    "https://www.youtube.com/watch?v=JT0Ul9cP5e4", # Matmatah - L'apologie
    "https://www.youtube.com/watch?v=M5AjPwN--1Q", # GiedRé
    "https://www.youtube.com/watch?v=nBI0bDH8W28", # Vianney - Pas là
    "https://www.youtube.com/watch?v=L_jWHffIx5E", # Smash Mouth - All Star
    "https://www.youtube.com/watch?v=rvrZJ5C_Nwg", # Kirin J Callinan - Big Enough
    "https://www.youtube.com/watch?v=O-MQC_G9jTU", # Bag Raiders - Shooting Stars
    "https://www.youtube.com/watch?v=PGNiXGX2nLU", # Dead Or Alive - You Spin Me Round
    "https://www.youtube.com/watch?v=dQw4w9WgXcQ", # Rick Asley - Never Gonna Give You Up
    "https://www.youtube.com/watch?v=BRTDC9Z5UdE", # Louise Attaque - Je t'emmene au vent
    "https://www.youtube.com/watch?v=s3O1Xro7oAI", # Johnny Hallyday - Allumer Le Feu
    "https://www.youtube.com/watch?v=2vjPBrBU-TM", # Sia - Chandelier
    "https://www.youtube.com/watch?v=aU_TQcyGkvY", # Kyo - Dernière danse
    "https://www.youtube.com/watch?v=BAkqJT_sMKQ", # Magic System - Magic in The Air
    "https://www.youtube.com/watch?v=FXovf5dsRTw", # Luis Fonsi - Despacito
    "https://www.youtube.com/watch?v=PfYnvDL0Qcw", # Lazy Town - We are Number One
    "https://www.youtube.com/watch?v=BEoGsr0WXVw", # The Living Tombstone - Beep Beep Im a Ship Remix
    "https://www.youtube.com/watch?v=lAIGb1lfpBw", # MitchiriNeko March
    "https://www.youtube.com/watch?v=5pOFKmk7ytU", # Animaniacs - Nations of the World
    "https://www.youtube.com/watch?v=wcibw-m8tRk", # Schnappi
    "https://www.youtube.com/watch?v=-XB7aftz6zY", # Belle - Notre dame de Paris
]